export const listOfMovies = [
  {
    id: 1,
    title: "Most Popolar Movies",
    content: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    type: "movie",
    genre: "Horror",
  },
  {
    id: 2,
    title: "Horror Movies",
    content: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    type: "movie",
    genre: "Comedies",
  },
  {
    id: 3,
    title: "Actions Movies",
    content: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    type: "movie",
    genre: "Suspense",
  },
  {
    id: 4,
    title: "Suspense Movies",
    content: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    type: "movie",
    genre: "Suspense",
  },
  {
    id: 5,
    title: "Romance Movies",
    content: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    type: "movie",
    genre: "Romance",
  },
];

export const moviesCatalog = [
  {
    id: 1,
    title: "Deadpool",
    img: "https://elcomercio.pe/resizer/g6QbVBSAUS23CeXawjpKUpJn3-o=/1200x800/smart/filters:format(jpeg):quality(75)/arc-anglerfish-arc2-prod-elcomercio.s3.amazonaws.com/public/MVUH5XA3MZDWFLVB7VEDHDCQSQ.jpg",
    url: "https://firebasestorage.googleapis.com/v0/b/shop-790d3.appspot.com/o/vimeoparty.mp4?alt=media&token=acce5963-ea6b-4add-9842-b9e068d392b3",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugit quos ducimus.",
    limit: "14",
    genre: "movies",
    year: "2022",
    isSeries: "false",
  },
  {
    id: 2,
    title: "Deadpool",
    img: "https://elcomercio.pe/resizer/g6QbVBSAUS23CeXawjpKUpJn3-o=/1200x800/smart/filters:format(jpeg):quality(75)/arc-anglerfish-arc2-prod-elcomercio.s3.amazonaws.com/public/MVUH5XA3MZDWFLVB7VEDHDCQSQ.jpg",
    url: "https://firebasestorage.googleapis.com/v0/b/shop-790d3.appspot.com/o/vimeoparty.mp4?alt=media&token=acce5963-ea6b-4add-9842-b9e068d392b3",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugit quos ducimus.",
    limit: "14",
    genre: "movies",
    year: "2021",
    isSeries: "false",
  },
  {
    id: 3,
    title: "Deadpool",
    img: "https://elcomercio.pe/resizer/g6QbVBSAUS23CeXawjpKUpJn3-o=/1200x800/smart/filters:format(jpeg):quality(75)/arc-anglerfish-arc2-prod-elcomercio.s3.amazonaws.com/public/MVUH5XA3MZDWFLVB7VEDHDCQSQ.jpg",
    url: "https://firebasestorage.googleapis.com/v0/b/shop-790d3.appspot.com/o/vimeoparty.mp4?alt=media&token=acce5963-ea6b-4add-9842-b9e068d392b3",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugit quos ducimus.",
    limit: "14",
    genre: "movies",
    year: "2020",
    isSeries: "false",
  },
  {
    id: 4,
    title: "Deadpool",
    img: "https://elcomercio.pe/resizer/g6QbVBSAUS23CeXawjpKUpJn3-o=/1200x800/smart/filters:format(jpeg):quality(75)/arc-anglerfish-arc2-prod-elcomercio.s3.amazonaws.com/public/MVUH5XA3MZDWFLVB7VEDHDCQSQ.jpg",
    url: "https://firebasestorage.googleapis.com/v0/b/shop-790d3.appspot.com/o/vimeoparty.mp4?alt=media&token=acce5963-ea6b-4add-9842-b9e068d392b3",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugit quos ducimus.",
    limit: "14",
    genre: "series",
    year: "2022",
    isSeries: "true",
  },
  {
    id: 5,
    title: "Deadpool",
    img: "https://elcomercio.pe/resizer/g6QbVBSAUS23CeXawjpKUpJn3-o=/1200x800/smart/filters:format(jpeg):quality(75)/arc-anglerfish-arc2-prod-elcomercio.s3.amazonaws.com/public/MVUH5XA3MZDWFLVB7VEDHDCQSQ.jpg",
    url: "https://firebasestorage.googleapis.com/v0/b/shop-790d3.appspot.com/o/vimeoparty.mp4?alt=media&token=acce5963-ea6b-4add-9842-b9e068d392b3",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugit quos ducimus.",
    limit: "14",
    genre: "series",
    year: "2015",
    isSeries: "true",
  },
  {
    id: 6,
    title: "Deadpool",
    img: "https://elcomercio.pe/resizer/g6QbVBSAUS23CeXawjpKUpJn3-o=/1200x800/smart/filters:format(jpeg):quality(75)/arc-anglerfish-arc2-prod-elcomercio.s3.amazonaws.com/public/MVUH5XA3MZDWFLVB7VEDHDCQSQ.jpg",
    url: "https://firebasestorage.googleapis.com/v0/b/shop-790d3.appspot.com/o/vimeoparty.mp4?alt=media&token=acce5963-ea6b-4add-9842-b9e068d392b3",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugit quos ducimus.",
    limit: "14",
    genre: "series",
    year: "2016",
    isSeries: "true",
  },
  {
    id: 7,
    title: "Deadpool",
    img: "https://elcomercio.pe/resizer/g6QbVBSAUS23CeXawjpKUpJn3-o=/1200x800/smart/filters:format(jpeg):quality(75)/arc-anglerfish-arc2-prod-elcomercio.s3.amazonaws.com/public/MVUH5XA3MZDWFLVB7VEDHDCQSQ.jpg",
    url: "https://firebasestorage.googleapis.com/v0/b/shop-790d3.appspot.com/o/vimeoparty.mp4?alt=media&token=acce5963-ea6b-4add-9842-b9e068d392b3",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugit quos ducimus.",
    limit: "14",
    genre: "series",
    year: "2012",
    isSeries: "true",
  },
  {
    id: 8,
    title: "Deadpool",
    img: "https://elcomercio.pe/resizer/g6QbVBSAUS23CeXawjpKUpJn3-o=/1200x800/smart/filters:format(jpeg):quality(75)/arc-anglerfish-arc2-prod-elcomercio.s3.amazonaws.com/public/MVUH5XA3MZDWFLVB7VEDHDCQSQ.jpg",
    url: "https://firebasestorage.googleapis.com/v0/b/shop-790d3.appspot.com/o/vimeoparty.mp4?alt=media&token=acce5963-ea6b-4add-9842-b9e068d392b3",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugit quos ducimus.",
    limit: "14",
    genre: "series",
    year: "2011",
    isSeries: "true",
  },
  {
    id: 9,
    title: "Deadpool",
    img: "https://elcomercio.pe/resizer/g6QbVBSAUS23CeXawjpKUpJn3-o=/1200x800/smart/filters:format(jpeg):quality(75)/arc-anglerfish-arc2-prod-elcomercio.s3.amazonaws.com/public/MVUH5XA3MZDWFLVB7VEDHDCQSQ.jpg",
    url: "https://firebasestorage.googleapis.com/v0/b/shop-790d3.appspot.com/o/vimeoparty.mp4?alt=media&token=acce5963-ea6b-4add-9842-b9e068d392b3",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugit quos ducimus.",
    limit: "14",
    genre: "series",
    year: "2016",
    isSeries: "true",
  },
  {
    id: 10,
    title: "Deadpool",
    img: "https://elcomercio.pe/resizer/g6QbVBSAUS23CeXawjpKUpJn3-o=/1200x800/smart/filters:format(jpeg):quality(75)/arc-anglerfish-arc2-prod-elcomercio.s3.amazonaws.com/public/MVUH5XA3MZDWFLVB7VEDHDCQSQ.jpg",
    url: "https://firebasestorage.googleapis.com/v0/b/shop-790d3.appspot.com/o/vimeoparty.mp4?alt=media&token=acce5963-ea6b-4add-9842-b9e068d392b3",
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugit quos ducimus.",
    limit: "14",
    genre: "series",
    year: "2017",
    isSeries: "true",
  },
];
